dist: xenial
sudo: required

language: go
go_import_path: github.com/sodafoundation/multi-cloud

go:
  - 1.13
  - tip

env:
  - TARGET=amd64
    GO111MODULE=on

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential gcc
  - sudo apt-get install -y librados-dev librbd-dev

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  exclude:

script:
  - ./install/CI/coverage
  - ./install/CI/test

after_success:
  # Clean SODA multi-cloud built data
  - bash <(curl -s https://codecov.io/bash)
  - make clean
