dist: xenial
sudo: required

language: go
go_import_path: github.com/opensds/multi-cloud
go:
  - 1.13
  - tip
  - docker-compose up -d

script:
  - ./install/CI/coverage
  - ./install/CI/test

matrix:
  fast_finish: true
  allow_failures:
  - go: tip

install:
  # Build OpenSDS multi-cloud container images
  - make docker
  - docker-compose up -d

after_success:
  - bash <(curl -s https://codecov.io/bash)
  # Clean OpenSDS multi-cloud built data
  - make clean
