version: '3'

services:

  api:
    image: opensdsio/multi-cloud/api
    ports:
      - 8088:8089
    environment:
      MICRO_SERVER_ADDRESS: ":8089"
      MICRO_REGISTRY: "mdns"

  backend:
    image: opensdsio/multi-cloud/backend
    environment:
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  s3:
    image: opensdsio/multi-cloud/s3
    environment:
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  dataflow:
    image: opensdsio/multi-cloud/dataflow
    environment:
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  datamover:
    image: opensdsio/multi-cloud/datamover
    environment:
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  datastore:
    image: mongo
    ports:
      - 27017:27017
